### ISSUE TITLE
registerForRemoteNotificationTypes: is not supported in iOS 8.0 and later.

### ISSUE THREAD

**Issue by evansobkowicz** [clearsightstudio/ProMotion-push#2]
I'm getting this error when building my app for iOS8.

It appears this should be used instead:
https://developer.apple.com/library/ios/documentation/uikit/reference/UIApplication_Class/index.html#//apple_ref/occ/instm/UIApplication/registerForRemoteNotifications

**Comment by squidpunch** [comment]
@jamonholmgren I took a pass at this #4

**Comment by jamonholmgren** [comment]
Thanks @squidpunch ! Version 0.3.0 is out with this feature.

Would you mind updating the README?

**Comment by squidpunch** [comment]
sure - I just pushed another PR to fix another issue.  I'll try and slate some time to update the readme on that PR :+1:
